### ISSUE TITLE
Open cordova-based apps from the sidebar

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#176]
### Open the rogerthat-payment cordova-based app from a sidebar item

- [x] Configure the homescreen item in build.yaml as follow:
  - action_type: cordova
  - action: rogerthat-payment

- [x] Extend the BUILD_CONSTANTS in build.yaml
```
BUILD_CONSTANTS:
  CORDOVA:
    apps:
      - rogerthat-payment
    plugins:
      - ...
      - ...
      - ...
```
- [x] Add APPS to release-scripts/cordova.py 
```
APPS = {
    'rogerthat-payment': {
        'url': '...',
        'dependencies': ['cordova-plugin-rogerthat-payment', '...']
    }
}
```
- [x] Extend release-scripts/cordova.py to clone the cordova app's repo and to copy the resources to the assets folder
- [x] Open the cordova app when clicking the homescreen item
