### ISSUE TITLE
Weird homescreen colors

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-android-client#388]
```yaml
HOMESCREEN:
  color: 7c7f80
  footer: true
  footer_alignment: bottom
  items:
  - action: news
    action_type: null
    color: null
    icon: fa-bullhorn
    params: {}
    text: Local News
  - action: news
    action_type: null
    icon: fa-newspaper-o
    params:
      feed_name: regional_news
    text: Regional News
  - action: messages
    action_type: null
    color: null
    icon: fa-envelope
    params: {}
    text: Messages
  - action: meldingskaart
    action_type: click
    color: null
    icon: fa-camera
    params: {}
    text: Report Card
  - action: agenda
    action_type: click
    color: null
    icon: fa-book
    params: {}
    text: Agenda
  - action: community_services
    action_type: null
    color: null
    icon: fa-university
    params:
      collapse: true
    text: Community Services
  - action: merchants
    action_type: null
    color: null
    icon: fa-user
    params: {}
    text: Merchants
  - action: associations
    action_type: null
    color: null
    icon: fa-users
    params: {}
    text: Associations
  - action: emergency_services
    action_type: null
    color: null
    icon: fa-medkit
    params: {}
    text: Care
  - action: friends
    action_type: null
    color: null
    icon: fa-smile-o
    params: {}
    text: Friends
  - action: scan
    action_type: null
    color: null
    icon: fa-qrcode
    params: {}
    text: Scan
  - action: profile
    action_type: null
    color: null
    icon: fa-user
    params: {}
    text: Profile
  - action: settings
    action_type: null
    color: null
    icon: fa-wrench
    params: {}
    text: Settings
  style: news
```

On Android only regional news has the correct color:

```java
public class NavigationConstants {

    public static NavigationItem[] getNavigationItems() {
        return new NavigationItem[]{
                new NavigationItem(FontAwesome.Icon.faw_bullhorn, null, "news", R.string.local_news, null, 0).setParams(null),
                new NavigationItem(FontAwesome.Icon.faw_newspaper_o, null, "news", R.string.regional_news, null, Color.parseColor("#7c7f80")).setParams("{\"feed_name\": \"regional_news\"}"),
                new NavigationItem(FontAwesome.Icon.faw_envelope, null, "messages", R.string.tab_messaging, null, 0).setParams(null),
                new NavigationItem(FontAwesome.Icon.faw_camera, "click", "584cc659f4811c0a9d05e51627547958e06ce75797fc3ebc99446f04b4b0a6c2", R.string.report_card, null, 0).setParams(null),
                new NavigationItem(FontAwesome.Icon.faw_book, "click", "df71fb0bd94cb72795bae4dce7bb6bd33efa6f7aa7ad11d78bfd6f734ca30e0b", R.string.agenda, null, 0).setParams(null),
                new NavigationItem(FontAwesome.Icon.faw_university, null, "community_services", R.string.community_service, null, 0).setParams("{\"collapse\": true}"),
                new NavigationItem(FontAwesome.Icon.faw_user, null, "merchants", R.string.merchants, null, 0).setParams(null),
                new NavigationItem(FontAwesome.Icon.faw_users, null, "associations", R.string.associations, null, 0).setParams(null),
                new NavigationItem(FontAwesome.Icon.faw_medkit, null, "emergency_services", R.string.care, null, 0).setParams(null),
                new NavigationItem(FontAwesome.Icon.faw_smile_o, null, "friends", R.string.tab_friends, null, 0).setParams(null),
                new NavigationItem(FontAwesome.Icon.faw_qrcode, null, "scan", R.string.scan, null, 0).setParams(null),
                new NavigationItem(FontAwesome.Icon.faw_user, null, "profile", R.string.profile, null, 0).setParams(null),
                new NavigationItem(FontAwesome.Icon.faw_wrench, null, "settings", R.string.settings, null, 0).setParams(null),
        };
    }
```

![image 2018-06-15 15 00 17](https://user-images.githubusercontent.com/17762105/41469251-d22eaf16-70ac-11e8-92b3-8f3eb17a0b0d.jpg)

On iOS it's correct:

![img_ba62358da7a2-1](https://user-images.githubusercontent.com/17762105/41469326-051a9cb4-70ad-11e8-81e8-403646cfd4d0.jpeg)
